# export RUBYOPT=-rubygems
export RUBYLIB=/var/lib/gems/1.8
export EDITOR=vim
export LSCOLORS="dxfxcxdxbxegedabagacad"
export M2_HOME=/opt/apache-maven-3.3.9
export PATH=$PATH:$M2_HOME/bin
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export JAVA_HOME=/opt/java
export NODE_HOME=/opt/nodejs
export KARAF_DEBUG=
